elfin_arm:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: elfin5_elfin_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
